ebook_metadata:
  title: ༄༅། །གྲུབ་ཐོབ་བརྒྱད་ཅུ་རྩ་བཞིའི་ལོ་རྒྱུས་སློབ་དཔོན་མི་འཇིགས་པ་སྦྱིན་པ་དཔལ་གྱིས་མཛད་པ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མི་འཇིགས་པ་སྦྱིན་པའི་དཔལ།
  sku: LEK-PHI-078
  layers:
  - book_title
  - author
  - chapter_title
  - yigchung
web_metadata:
  title:
    en: The Lives of the Eighty-Four Mahasiddhas
    bo: གྲུབ་ཐོབ་བརྒྱད་ཅུ་རྩ་བཞིའི་ལོ་རྒྱུས།
  collection:
    en: Lekshey Ling Philosophy Series–  Book 78
    bo: ལེགས་བཤད་གླིང་རིགས་པའི་གཞུང་ལུགས།–  དེབ། ༧༨
  author:
    en: Mijigpa Jinpai Pal
    bo: མི་འཇིགས་པ་སྦྱིན་པའི་དཔལ།
  pusblisher:
    en: Lekshey Ling Publications
    bo: ཀརྨ་ལེགས་བཤད་གླིང།
  sku: LEK-PHI-078
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LEK-PHI-078.epub
  description:
    en: ''
    bo: ''
